sudo: true
dist: focal
install:
  - sudo apt update
  - sudo apt -y install make
  - make deps-lin
  - tlmgr update --self
  - tlmgr update --all

script:
  - make clean
  - make update
  - make debug
  - make quick
  - make bib
  - make all
  - echo "testme"|make rename
  - make quick
  - file testme.pdf
  - make llncs
  - make quick
  - make ieee
  - make quick
  - cat build.sh.log

notifications:
  email:
    - alex@willner.ws
