name: macOS
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          ls -la
          ls -la lib
      - name: Init
        run: |
          git clone https://github.com/tubav/Core.git lib
          brew install mactex plantuml graphviz gnuplot aspell r
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self --all
          sudo tlmgr install texliveonfly glossaries biber collection-fontsrecommended IEEEtran xindy
      - name: Debug
        run: |
          make debug
      - name: Test
        run: |
          make quick
          make bib
          make all
          echo "testme"|make rename
          make quick
          file testme.pdf
          make llncs
          make quick
          make ieee
          make quick
      - name: Show Log
        run: cat build.sh.log
        if: always()
