name: macOS
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          ls -la
          ls -la lib
      - name: Init
        run: |
          git clone https://github.com/tubav/Core.git lib
          make deps-mac || sudo tlmgr install texliveonfly biber collection-fontsrecommended IEEEtran xindy
          eval "$(/usr/libexec/path_helper)"
      - name: Debug
        run: |
          eval "$(/usr/libexec/path_helper)"
          make debug
      - name: Test
        run: |
          export PATH="/Library/TeX/texbin/:$PATH"
          eval "$(/usr/libexec/path_helper)"
          make quick
          make bib
          make all
          echo "testme"|make rename
          make quick
          file testme.pdf
          make llncs
          make quick
          make ieee
          make quick
      - name: Show Log
        run: cat build.sh.log
        if: always()
