name: LaTeX Paper Github Action
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        run: |
          ls -la
          ls -la lib
          apt update && apt install sudo
          sudo apt update
          sudo apt -y install make git
      - name: Init
        run: |
          make update
          make deps-lin
      - name: Debug
        run: |
          make debug
      - name: Test
        run: |
          make quick
          make bib
          make all
          echo "testme"|make rename
          make quick
          file testme.pdf
          make llncs
          make quick
          make ieee
          make quick
          cat build.sh.log
